addr: ":8000"
game: ":2000"

driver: sqlite3
db: development.bin
#db: ../data/development.bin

level: info

games:
    - addr: "localhost:8000"
    #- addr: "oniproject-lain.rhcloud.com:8000"
      rpc: ":1234"
      minid: 10
      maxid: 100000
      local: true

